-- SELECT * FROM me.books;

drop table books;

create table BOOKS (    
BOOK_ID integer primary key,    
TITLE varchar (40),  
LANGUAGES varchar (40), 
EXIT_DATE varchar (40),
AUTHOR_ID integer references BOOKS(AUTHOR_ID),    
GENER_ID integer references BOOKS(GENER_ID),
PUBLISHER_ID integer references BOOKS(PUBLISHER_ID),
CLIENT_ID integer references BOOKS(CLIENT_ID));



insert into BOOKS (BOOK_ID, TITLE, LANGUAGES, EXIT_DATE, AUTHOR_ID, GENER_ID, PUBLISHER_ID, CLIENT_ID)
values (1, 'ORGOGLIO E PREGIUDIZIO', 'ENGLISH', '1813', NULL, NULL, NULL, NULL);
insert into BOOKS (BOOK_ID, TITLE, LANGUAGES, EXIT_DATE, AUTHOR_ID, GENER_ID, PUBLISHER_ID, CLIENT_ID)
values (2, 'IL SIGNORE DEGLI ANELLI', 'ENGLISH', '1955', NULL, NULL, NULL, NULL);
insert into BOOKS (BOOK_ID, TITLE, LANGUAGES, EXIT_DATE, AUTHOR_ID, GENER_ID, PUBLISHER_ID, CLIENT_ID)
values (3, 'IL PROFETA', 'ENGLISH', '1923', NULL, NULL, NULL, NULL);
insert into BOOKS (BOOK_ID, TITLE, LANGUAGES, EXIT_DATE, AUTHOR_ID, GENER_ID, PUBLISHER_ID, CLIENT_ID)
values (4, 'HARRY POTTER', 'ENGLISH', '1997', NULL, NULL, NULL, NULL);
insert into BOOKS (BOOK_ID, TITLE, LANGUAGES, EXIT_DATE, AUTHOR_ID, GENER_ID, PUBLISHER_ID, CLIENT_ID)
values (5, 'SE QUESTO E UN UOMO', 'ITALIEN', '1947', NULL, NULL, NULL, NULL);
insert into BOOKS (BOOK_ID, TITLE, LANGUAGES, EXIT_DATE, AUTHOR_ID, GENER_ID, PUBLISHER_ID, CLIENT_ID)
values (6, 'LA BIBBIA', 'FRENCH', '1300', NULL, NULL, NULL, NULL);
insert into BOOKS (BOOK_ID, TITLE, LANGUAGES, EXIT_DATE, AUTHOR_ID, GENER_ID, PUBLISHER_ID, CLIENT_ID)
values (7, 'CIME TEMPESTOSE', 'FRENCH', '1938', NULL, NULL, NULL, NULL);
insert into BOOKS (BOOK_ID, TITLE, LANGUAGES, EXIT_DATE, AUTHOR_ID, GENER_ID, PUBLISHER_ID, CLIENT_ID)
values (8, '1984', 'ENGLISH', '1984', NULL, NULL, NULL, NULL);
insert into BOOKS (BOOK_ID, TITLE, LANGUAGES, EXIT_DATE, AUTHOR_ID, GENER_ID, PUBLISHER_ID, CLIENT_ID)
values (9, 'I PROMESSI SPOSI', 'ITALIEN', '1813', NULL, NULL, NULL, NULL);
insert into BOOKS (BOOK_ID, TITLE, LANGUAGES, EXIT_DATE, AUTHOR_ID, GENER_ID, PUBLISHER_ID, CLIENT_ID)
values (10, 'LA DIVINA COMMEDIA', 'ITALIEN', '1765', NULL, NULL, NULL, NULL);

