DROP TABLE CLIENTS;

create table CLIENTS (    
CLIENT_ID integer primary key,    
FIRST_NAME varchar (40),  
LAST_NAME varchar (40), 
BIRTHDAY_DATE varchar (40),
CITY_NAME varchar (40),    
GENER_ID integer references CLIENTS (GENER_ID),
AUTHOR_ID integer references CLIENTS(AUTHOR_ID));



insert into CLIENTS (CLIENT_ID, FIRST_NAME, LAST_NAME, BIRTHDAY_DATE, CITY_NAME, GENER_ID, AUTHOR_ID)
values (21, 'FRANCESCA', 'LAI', '1997', 'CAGLIARI', NULL, NULL);
insert into CLIENTS (CLIENT_ID, FIRST_NAME, LAST_NAME, BIRTHDAY_DATE, CITY_NAME, GENER_ID, AUTHOR_ID)
values (22, 'ALESSANDRO', 'BORGHI', '1952', 'LIVORNO', NULL, NULL);
insert into CLIENTS (CLIENT_ID, FIRST_NAME, LAST_NAME, BIRTHDAY_DATE, CITY_NAME, GENER_ID, AUTHOR_ID)
values (23, 'ALESSANDRO', 'FRESU', '1937', 'ARESE', NULL, NULL);
insert into CLIENTS (CLIENT_ID, FIRST_NAME, LAST_NAME, BIRTHDAY_DATE, CITY_NAME, GENER_ID, AUTHOR_ID)
values (24, 'LUCA', 'MELIS', '1963', 'MILANO', NULL, NULL);
insert into CLIENTS (CLIENT_ID, FIRST_NAME, LAST_NAME, BIRTHDAY_DATE, CITY_NAME, GENER_ID, AUTHOR_ID)
values (25, 'LUCIANA', 'PASTI', '1986', 'TRIESTE', NULL, NULL);
insert into CLIENTS (CLIENT_ID, FIRST_NAME, LAST_NAME, BIRTHDAY_DATE, CITY_NAME, GENER_ID, AUTHOR_ID)
values (26, 'CRISTEL', 'ORTU', '2000', 'ROMA', NULL, NULL);
insert into CLIENTS (CLIENT_ID, FIRST_NAME, LAST_NAME, BIRTHDAY_DATE, CITY_NAME, GENER_ID, AUTHOR_ID)
values (27, 'DOROTY', 'PERKINS', '1995', 'NAPOLI', NULL, NULL);
insert into CLIENTS (CLIENT_ID, FIRST_NAME, LAST_NAME, BIRTHDAY_DATE, CITY_NAME, GENER_ID, AUTHOR_ID)
values (28, 'ALICE', 'VERONESI', '2002', 'BENEVENTO', NULL, NULL);
insert into CLIENTS (CLIENT_ID, FIRST_NAME, LAST_NAME, BIRTHDAY_DATE, CITY_NAME, GENER_ID, AUTHOR_ID)
values (29, 'GIANNI', 'BORGHI', '1962', 'LIVORNO', NULL, NULL);
insert into CLIENTS (CLIENT_ID, FIRST_NAME, LAST_NAME, BIRTHDAY_DATE, CITY_NAME, GENER_ID, AUTHOR_ID)
values (30, 'ALESSANDRO', 'MELIS', '1997', 'FIRENZE', NULL, NULL);




commit;


